# Generated by Django 3.2.5 on 2022-01-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, 'Technology'), (1, 'Product'), (2, 'Marketing'), (3, 'Design')], verbose_name='Job Classification')),
                ('job_name', models.CharField(max_length=250, verbose_name='Job name')),
                ('job_city', models.SmallIntegerField(choices=[(0, 'Helsinki'), (1, 'Tampere'), (2, 'Oulu')], verbose_name='Basement')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='Job Description')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='Job requirement')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(verbose_name='Modified Date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
