# Generated by Django 3.2.5 on 2022-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Candidate Id')),
                ('username', models.CharField(max_length=135, verbose_name='Name')),
                ('city', models.CharField(max_length=135, verbose_name='City')),
                ('phone', models.CharField(max_length=135, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='Email')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='Position')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='Hometown')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='Gender')),
                ('Candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='Remark')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='Bachelor School')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='Master School')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='Doctor School')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='Major')),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=135, verbose_name='Degree')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='General Test Score')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Paper Test Score')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='First Score')),
                ('first_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Learning Ability Score')),
                ('first_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Professional Score')),
                ('first_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantages')),
                ('first_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Hold', 'Hold'), ('Reject', 'Reject')], max_length=256, verbose_name='First Result')),
                ('first_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='First Recommend Position')),
                ('first_interviewer', models.CharField(blank=True, max_length=256, verbose_name='First Interviewer')),
                ('first_remark', models.CharField(blank=True, max_length=135, verbose_name='First Remark')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Second Score')),
                ('second_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Second Learning Ability')),
                ('second_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Second Professional Competency')),
                ('second_pursue_of_excellence', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Pursue Of Excellence')),
                ('second_communication_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Communication Ability')),
                ('second_pressure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Pressure Score')),
                ('second_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Second Interview Advantage')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Second Interview Disadvantage')),
                ('second_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Hold', 'Hold'), ('Reject', 'Reject')], max_length=256, verbose_name='Second Result')),
                ('second_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Second Interview Recommend Position')),
                ('second_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Second Interviewer')),
                ('second_remark', models.CharField(blank=True, max_length=135, verbose_name='Second Interview Remark')),
                ('hr_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score')),
                ('hr_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score Of Responsibility')),
                ('hr_communication_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score Of Communication Ability')),
                ('hr_logic_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score Of Ability')),
                ('hr_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score Of Potential')),
                ('hr_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='Final Score Of Stability')),
                ('hr_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Final Score Of Advantage')),
                ('hr_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Final Score Of Disadvantage')),
                ('hr_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Hold', 'Hold'), ('Reject', 'Reject')], max_length=256, verbose_name='Final Score Of Result')),
                ('hr_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Final Test Interviewer')),
                ('hr_remark', models.CharField(blank=True, max_length=256, verbose_name='Final Score Of Remark')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='Final Test Creator')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Final Test Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Final Test Modified Date')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='Final Test Last Editor')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'candidate',
            },
        ),
    ]
